-- EDA (Exploratory Data Analysis)
SELECT * FROM category;
SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM order_items;
SELECT * FROM orders;
SELECT * FROM payments;
SELECT * FROM products;
SELECT * FROM shippings;
SELECT * FROM sellers;
SELECT 
	DISTINCT payment_status
FROM payments;

SELECT *
FROM shippings
WHERE return_date IS NOT NULL;

-- EDA ends here. 

/* Advance Business 
Problem Statements */ 

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/
--Method-I (Subquery)
SELECT 
  t1.p_name, 
  (
    t2.price * t1.total_quantity_sold
  ) AS total_sales_value 
FROM 
  (
    SELECT 
      p.product_name as p_name, 
      p.product_id, 
      ROUND(
        SUM(oi.quantity), 
        2
      ) AS total_quantity_sold 
    FROM 
      products AS p 
      JOIN order_items AS oi ON p.product_id = oi.product_id 
    GROUP BY 
      1, 
      2
  ) as t1 
  JOIN products AS t2 ON t1.product_id = t2.product_id 
ORDER BY 
  total_sales_value DESC 
LIMIT 
  10;


--Method-II (creating new column) 
ALTER TABLE 
  order_items 
ADD 
  COLUMN total_sale FLOAT;
UPDATE 
  order_items 
SET 
  total_sale = quantity * price_per_unit;
SELECT 
  p.product_name, 
  COUNT(o.order_id) AS sale_count, 
  SUM(oi.total_sale) AS total_sale_value 
FROM 
  orders AS o 
  JOIN order_items AS oi ON o.order_id = oi.order_id 
  JOIN products AS p ON p.product_id = oi.product_id 
GROUP BY 
  1 
ORDER BY 
  SUM(oi.total_sale) DESC 
LIMIT 
  10;


/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
-- Method-I (With CTE)
WITH CTE AS (
  SELECT 
    SUM(total_sale) AS s_t 
  FROM 
    order_items
) 
SELECT 
  c.category_name, 
  SUM(oi.total_sale) AS category_sale, 
  (
    SUM(oi.total_sale)/ t.s_t
  ) * 100 AS percentage_contribution 
FROM 
  order_items AS oi 
  JOIN products AS p ON oi.product_id = p.product_id 
  JOIN category AS c ON p.category_id = c.category_id CROSS 
  JOIN CTE AS t 
GROUP BY 
  c.category_name, 
  t.s_t;


-- Method-II (With Subquery)

SELECT 
  c.category_name, 
  SUM(oi.total_sale) AS category_sale, 
  (
    SUM(oi.total_sale)/(
      SELECT 
        SUM(total_sale) 
      FROM 
        order_items
    )
  ) * 100 AS percentage_contribution 
FROM 
  order_items AS oi 
  JOIN products AS p ON oi.product_id = p.product_id 
  JOIN category AS c ON p.category_id = c.category_id 
GROUP BY 
  1;

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
--Method-I (Using simple join)
SELECT 
  c.customer_id, 
  c.first_name, 
  c.last_name, 
  SUM(oi.total_sale)/ COUNT(o.order_id) AS AOV, 
  COUNT(o.order_id) AS order_counts 
FROM 
  customers AS c 
  JOIN orders AS o ON c.customer_id = o.customer_id 
  JOIN order_items AS oi ON o.order_id = oi.order_id 
GROUP BY 
  1, 
  2, 
  3 
HAVING 
  COUNT(o.order_id) > 5 
ORDER BY 
  4 DESC;


-- Method-II (Using Common Table Expression)

WITH no_orders AS(
  SELECT 
    c.customer_id, 
    COUNT(o.customer_id) AS o_counts 
  FROM 
    customers AS c 
    JOIN orders AS o ON c.customer_id = o.customer_id 
  GROUP BY 
    1
) 
SELECT 
  c.customer_id, 
  c.first_name, 
  c.last_name, 
  SUM(oi.total_sale)/(no_orders.o_counts) AS AOV 
FROM 
  customers AS c 
  JOIN orders AS o ON c.customer_id = o.customer_id 
  JOIN order_items AS oi ON o.order_id = oi.order_id 
  JOIN no_orders ON c.customer_id = no_orders.customer_id 
GROUP BY 
  1, 
  2, 
  3, 
  no_orders.o_counts 
HAVING 
  no_orders.o_counts > 5 
ORDER BY 
  4 DESC;


/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/

-- Note :- Since we are in 2025 and data's latest date is Jul-2024. We we cannot use interval function directly
WITH max_date AS (
  SELECT 
    MAX(order_date) AS max_dt 
  FROM 
    orders
) 
SELECT 
  order_year, 
  order_month, 
  monthly_sale, 
  LAG(monthly_sale) OVER(
    ORDER BY 
      order_year, 
      order_month
  ) 
FROM 
  (
    SELECT 
      EXTRACT(
        YEAR 
        FROM 
          o.order_date
      ) AS order_year, 
      EXTRACT(
        MONTH 
        FROM 
          o.order_date
      ) AS order_month, 
      ROUND(
        SUM(oi.total_sale):: numeric, 
        2
      ) AS monthly_sale 
    FROM 
      orders AS o 
      JOIN order_items AS oi ON o.order_id = oi.order_id 
      JOIN max_date AS md ON TRUE 
    WHERE 
      o.order_date >= md.max_dt - INTERVAL '12 MONTHS' 
    GROUP BY 
      1, 
      2 
    ORDER BY 
      1, 
      2
  );

	
/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/
-- Method I - Using Join
SELECT 
  DISTINCT t1.customer_id 
FROM 
  customers AS t1 
  LEFT JOIN orders AS t2 ON t1.customer_id = t2.customer_id 
WHERE 
  t2.customer_id IS NULL;


-- Method - II Using sub query
SELECT 
  DISTINCT customer_id 
FROM 
  customers 
WHERE 
  customer_id NOT IN (
    SELECT 
      DISTINCT customer_id 
    FROM 
      orders
  );


/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/

SELECT 
  * 
FROM 
  (
    SELECT 
      *, 
      RANK() OVER(
        PARTITION BY state 
        ORDER BY 
          total_sale
      ) AS rank_over_category_sale 
    FROM 
      (
        SELECT 
          c.state, 
          ca.category_name, 
          ROUND(
            SUM(oi.total_sale):: numeric, 
            2
          ) AS total_sale 
        FROM 
          category AS ca 
          JOIN products AS p ON ca.category_id = p.category_id 
          JOIN order_items AS oi ON p.product_id = oi.product_id 
          JOIN orders AS o ON oi.order_id = o.order_id 
          JOIN customers AS c ON o.customer_id = c.customer_id 
        GROUP BY 
          1, 
          2 
        ORDER BY 
          1
      )
  ) 
WHERE 
  rank_over_category_sale = 1;

  
-- Method-II(Using Subquery)
SELECT 
  * 
FROM 
  (
    SELECT 
      *, 
      RANK() OVER(
        PARTITION BY state 
        ORDER BY 
          total_sale
      ) AS rank_over_category_sale 
    FROM 
      (
        SELECT 
          c.state, 
          ca.category_name, 
          ROUND(
            SUM(oi.total_sale):: numeric, 
            2
          ) AS total_sale 
        FROM 
          category AS ca 
          JOIN products AS p ON ca.category_id = p.category_id 
          JOIN order_items AS oi ON p.product_id = oi.product_id 
          JOIN orders AS o ON oi.order_id = o.order_id 
          JOIN customers AS c ON o.customer_id = c.customer_id 
        GROUP BY 
          1, 
          2 
        ORDER BY 
          1
      )
  ) 
WHERE 
  rank_over_category_sale = 1;


/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/
SELECT 
	c.customer_id,
	CONCAT(c.first_name, ' ',  c.last_name) as full_name,
	SUM(total_sale) as CLTV,
	DENSE_RANK() OVER( ORDER BY SUM(total_sale) DESC) as cx_ranking
FROM orders as o
JOIN 
customers as c
ON c.customer_id = o.customer_id
JOIN 
order_items as oi
ON oi.order_id = o.order_id
GROUP BY 1, 2

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/
SELECT 
	i.inventory_id,
	p.product_name,
	i.stock as current_stock_left,
	i.last_stock_date,
	i.warehouse_id
FROM inventory as i
join 
products as p
ON p.product_id = i.product_id
WHERE stock < 10

/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/
SELECT 
	c.*,
	o.*,
	s.shipping_providers,
s.shipping_date - o.order_date as days_took_to_ship
FROM orders as o
JOIN
customers as c
ON c.customer_id = o.customer_id
JOIN 
shippings as s
ON o.order_id = s.order_id
WHERE s.shipping_date - o.order_date > 3

/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT 
	p.payment_status,
	COUNT(*) as total_cnt,
	COUNT(*)::numeric/(SELECT COUNT(*) FROM payments)::numeric * 100
FROM orders as o
JOIN
payments as p
ON o.order_id = p.order_id
GROUP BY 1;

/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/
WITH top_sellers
AS
(SELECT 
	s.seller_id,
	s.seller_name,
	SUM(oi.total_sale) as total_sale
FROM orders as o
JOIN
sellers as s
ON o.seller_id = s.seller_id
JOIN 
order_items as oi
ON oi.order_id = o.order_id
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 5
),

sellers_reports
AS
(SELECT 
	o.seller_id,
	ts.seller_name,
	o.order_status,
	COUNT(*) as total_orders
FROM orders as o
JOIN 
top_sellers as ts
ON ts.seller_id = o.seller_id
WHERE 
	o.order_status NOT IN ('Inprogress', 'Returned')
	
GROUP BY 1, 2, 3
)
SELECT 
	seller_id,
	seller_name,
	SUM(CASE WHEN order_status = 'Completed' THEN total_orders ELSE 0 END) as Completed_orders,
	SUM(CASE WHEN order_status = 'Cancelled' THEN total_orders ELSE 0 END) as Cancelled_orders,
	SUM(total_orders) as total_orders,
	SUM(CASE WHEN order_status = 'Completed' THEN total_orders ELSE 0 END)::numeric/
	SUM(total_orders)::numeric * 100 as successful_orders_percentage
	
FROM sellers_reports
GROUP BY 1, 2;

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/
SELECT 
	product_id,
	product_name,
	profit_margin,
	DENSE_RANK() OVER( ORDER BY profit_margin DESC) as product_ranking
FROM
(SELECT 
	p.product_id,
	p.product_name,
	-- SUM(total_sale - (p.cogs * oi.quantity)) as profit,
	SUM(total_sale - (p.cogs * oi.quantity))/sum(total_sale) * 100 as profit_margin
FROM order_items as oi
JOIN 
products as p
ON oi.product_id = p.product_id
GROUP BY 1, 2
) as t1;

/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
SELECT * FROM order_items;
SELECT DISTINCT order_status FROM orders;
SELECT * FROM products;
--Method-I
WITH CTE AS (SELECT 
p.product_name, COUNT(o.order_status) AS sold_status
FROM order_items AS oi
JOIN products AS p 
ON oi.product_id = p.product_id
JOIN orders AS o 
ON oi.order_id = o.order_id
GROUP BY 1
)

SELECT p.product_name,o.order_status, COUNT(o.order_status) AS return_counts,
ROUND((COUNT(order_status)::numeric / CTE.sold_status::numeric),2) AS return_rate
FROM order_items AS oi 
JOIN products AS p
ON oi.product_id = p.product_id
JOIN orders AS o 
ON oi.order_id = o.order_id
JOIN CTE
ON p.product_name = CTE.product_name
WHERE o.order_status = 'Returned'
GROUP BY 1,2,CTE.sold_status
ORDER BY 3 DESC;

--METHOD-II
SELECT 
	p.product_id,
	p.product_name,
	COUNT(*) as total_unit_sold,
	SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) as total_returned,
	SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END)::numeric/COUNT(*)::numeric * 100 as return_percentage
FROM order_items as oi
JOIN 
products as p
ON oi.product_id = p.product_id
JOIN orders as o
ON o.order_id = oi.order_id
GROUP BY 1, 2
ORDER BY 5 DESC;

/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/
SELECT 
  c.*, 
  o.*, 
  p.payment_date, 
  p.payment_status, 
  sh.delivery_status 
FROM 
  orders AS o 
  JOIN shippings AS sh ON o.order_id = sh.order_id 
  JOIN payments AS p ON o.order_id = p.order_id 
  JOIN customers AS c ON o.customer_id = c.customer_id 
WHERE 
  p.payment_status = 'Payment Successed' 
  AND sh.delivery_status = 'Shipped';

/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/
WITH CTE AS 
(
SELECT s.seller_id,s.seller_name,s.origin
FROM sellers AS s
LEFT JOIN 
(SELECT s.*, o.order_date AS o_date, ROUND(SUM(oi.total_sale)::numeric,2) AS total_sales
FROM sellers AS s
JOIN orders AS o
ON s.seller_id = o.seller_id
JOIN order_items AS oi 
ON o.order_id = oi.order_id
WHERE o.order_date >= (SELECT MAX(order_date) FROM orders) - INTERVAL'6 Month'
GROUP BY 1,o.order_date) AS sub
ON s.seller_id =  sub.seller_id
WHERE sub.total_sales IS NULL
)

SELECT CTE.seller_id, CTE.seller_name, CTE.origin,
MAX(o.order_date) AS latest_date,
SUM(oi.total_sale) AS total_sales
FROM CTE
JOIN orders AS o
ON CTE.seller_id = o.seller_id
JOIN order_items AS oi 
ON o.order_id =  oi.order_id
GROUP BY 1,2,3;

/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/

SELECT 
c_full_name as customers,
total_orders,
total_return,
CASE
	WHEN total_return > 5 THEN 'Returning_customers' ELSE 'New'
END as cx_category
FROM
(SELECT 
	CONCAT(c.first_name, ' ', c.last_name) as c_full_name,
	COUNT(o.order_id) as total_orders,
	SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) as total_return	
FROM orders as o
JOIN 
customers as c
ON c.customer_id = o.customer_id
JOIN
order_items as oi
ON oi.order_id = o.order_id
GROUP BY 1);

/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/

SELECT * FROM 
(SELECT 
	c.state,
	CONCAT(c.first_name, ' ', c.last_name) as customers,
	COUNT(o.order_id) as total_orders,
	SUM(total_sale) as total_sale,
	DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(o.order_id) DESC) as rank
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
customers as c
ON 
c.customer_id = o.customer_id
GROUP BY 1, 2
) as t1
WHERE rank <=5;

/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/
SELECT 
	s.shipping_providers,
	COUNT(o.order_id) as order_handled,
	SUM(oi.total_sale) as total_sale,
	COALESCE(AVG(s.return_date - s.shipping_date), 0) as average_days
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
shippings as s
ON 
s.order_id = o.order_id
GROUP BY 1;


/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result

Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/
WITH last_year_sale
as
(
SELECT 
	p.product_id,
	p.product_name,
	SUM(oi.total_sale) as revenue
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
products as p
ON 
p.product_id = oi.product_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2022
GROUP BY 1, 2
),

current_year_sale
AS
(
SELECT 
	p.product_id,
	p.product_name,
	SUM(oi.total_sale) as revenue
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
products as p
ON 
p.product_id = oi.product_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2023
GROUP BY 1, 2
)

SELECT
	cs.product_id,
	ls.revenue as last_year_revenue,
	cs.revenue as current_year_revenue,
	ls.revenue - cs.revenue as rev_diff,
	ROUND((cs.revenue - ls.revenue)::numeric/ls.revenue::numeric * 100, 2) as reveneue_dec_ratio
FROM last_year_sale as ls
JOIN
current_year_sale as cs
ON ls.product_id = cs.product_id
WHERE 
	ls.revenue > cs.revenue
ORDER BY 5 DESC
LIMIT 10;


/*
Final Task
-- Store Procedure
create a function as soon as the product is sold the the same quantity should reduced from inventory table
after adding any sales records it should update the stock in the inventory table based on the product and qty purchased
*/
CREATE OR REPLACE PROCEDURE add_sales
(
p_order_id INT,
p_customer_id INT,
p_seller_id INT,
p_order_item_id INT,
p_product_id INT,
p_quantity INT
)
LANGUAGE plpgsql
AS $$ 

DECLARE
v_count INT;
v_price FLOAT;
v_product VARCHAR(50);

BEGIN
-- Checking if the ordered product is available in the inventory 
	SELECT price, product_name
		INTO
		v_price,v_product
	FROM products	
	WHERE product_id = p_product_id;
	
	SELECT COUNT(*)
		   INTO
		   v_count
	FROM inventory
	WHERE product_id = p_product_id
		  AND stock >= p_quantity;

	IF v_count > 0 THEN 
	--We need to update the order/order_items/inventory tables as these tables gets affected after each complete order
		INSERT INTO orders(order_id,order_date,customer_id,seller_id)
		VALUES
		(p_order_id, CURRENT_DATE, p_customer_id, p_seller_id);

		INSERT INTO order_items(order_item_id,order_id,product_id,quantity,price_per_unit,total_sale)
		VALUES
		(p_order_item_id,p_order_id,p_product_id,p_quantity,v_price, v_price*p_quantity);

		UPDATE inventory
		SET stock = stock - p_quantity
		WHERE product_id = p_product_id;

		RAISE NOTICE 'Thank you for shopping. product: % sale is added and inventory is updated', v_product;

	ELSE 
		RAISE NOTICE 'Thankyou for your time unfortunately the product : % is not available', v_product;

	END IF;

END;
$$

-- Calling Procedure

CALL add_sales
(
30003,2,5,30004,5,1
);
